#!/usr/bin/env python3
"""
Upload all Spider SQLite databases to Turso

This script:
1. Finds all .sqlite files in data/spider/database/
2. Creates Turso databases for each
3. Uploads the SQLite files via Turso CLI
4. Generates a token mapping file
"""

import os
import subprocess
import sys
from pathlib import Path

# Add parent directory to path
sys.path.insert(0, str(Path(__file__).parent.parent))


def run_command(cmd, capture_output=True):
    """Run shell command and return output"""
    try:
        result = subprocess.run(
            cmd,
            shell=True,
            capture_output=capture_output,
            text=True,
            check=True
        )
        return result.stdout.strip() if capture_output else None
    except subprocess.CalledProcessError as e:
        print(f"Error running command: {cmd}")
        print(f"Error: {e.stderr}")
        return None


def find_sqlite_databases():
    """Find all Spider SQLite databases"""
    spider_dir = Path("data/spider/database")

    if not spider_dir.exists():
        print(f"Error: Spider directory not found: {spider_dir}")
        return []

    databases = []

    for db_dir in spider_dir.iterdir():
        if not db_dir.is_dir():
            continue

        # Look for .sqlite file
        sqlite_files = list(db_dir.glob("*.sqlite"))

        if sqlite_files:
            databases.append({
                "name": db_dir.name,
                "path": sqlite_files[0],
                "size": sqlite_files[0].stat().st_size
            })

    return databases


def upload_database(db_info):
    """Upload a single database to Turso"""
    db_name = db_info["name"]
    db_path = db_info["path"]

    print(f"\n{'='*60}")
    print(f"Uploading: {db_name}")
    print(f"File: {db_path}")
    print(f"Size: {db_info['size'] / 1024:.1f} KB")
    print(f"{'='*60}")

    # Check if database already exists
    check_cmd = f"turso db show {db_name} 2>/dev/null"
    existing = run_command(check_cmd)

    if existing:
        print(f"⚠️  Database '{db_name}' already exists")
        response = input("Delete and recreate? (y/n): ")
        if response.lower() == 'y':
            print(f"Deleting {db_name}...")
            run_command(f"turso db destroy {db_name} --yes", capture_output=False)
        else:
            print(f"Skipping {db_name}")
            return False

    # Create database from SQLite file
    print(f"Creating Turso database from {db_path}...")
    create_cmd = f'turso db create {db_name} --from-file "{db_path}"'
    result = run_command(create_cmd, capture_output=False)

    if result is None:
        # Command executed successfully (check=True would have raised)
        print(f"✅ Successfully uploaded {db_name}")
        return True
    else:
        print(f"❌ Failed to upload {db_name}")
        return False


def generate_token_file(databases):
    """Generate .env.turso file with tokens for all databases"""
    print(f"\n{'='*60}")
    print("Generating auth tokens...")
    print(f"{'='*60}")

    tokens = {}

    for db_info in databases:
        db_name = db_info["name"]
        print(f"Creating token for {db_name}...")

        token_cmd = f"turso db tokens create {db_name}"
        token = run_command(token_cmd)

        if token:
            tokens[db_name] = token
            print(f"✅ Token generated for {db_name}")
        else:
            print(f"❌ Failed to generate token for {db_name}")

    # Write to .env.turso
    env_file = Path(".env.turso")

    with open(env_file, 'w') as f:
        f.write("# Turso database tokens\n")
        f.write("# Generated by upload_to_turso.py\n\n")

        for db_name, token in tokens.items():
            env_var = f"TURSO_TOKEN_{db_name.upper().replace('-', '_')}"
            f.write(f"{env_var}={token}\n")

    print(f"\n✅ Tokens saved to {env_file}")
    print("Add these to your .env file or Railway environment variables")


def main():
    """Main upload process"""
    print("="*60)
    print("Turso Upload Script - Spider Benchmark Databases")
    print("="*60)

    # Check Turso CLI is installed
    print("\nChecking Turso CLI...")
    turso_version = run_command("turso --version")

    if not turso_version:
        print("❌ Turso CLI not found. Install with:")
        print("   curl -sSfL https://get.tur.so/install.sh | bash")
        sys.exit(1)

    print(f"✅ Turso CLI installed: {turso_version}")

    # Check authentication
    print("\nChecking Turso authentication...")
    whoami = run_command("turso auth whoami")

    if not whoami or "not logged in" in whoami.lower():
        print("❌ Not logged in to Turso. Run:")
        print("   turso auth login")
        sys.exit(1)

    print(f"✅ Logged in as: {whoami}")

    # Find databases
    print("\nFinding Spider databases...")
    databases = find_sqlite_databases()

    if not databases:
        print("❌ No SQLite databases found in data/spider/database/")
        sys.exit(1)

    print(f"✅ Found {len(databases)} databases")

    # Show summary
    total_size = sum(db["size"] for db in databases)
    print(f"\nTotal size: {total_size / (1024 * 1024):.2f} MB")
    print("\nDatabases to upload:")
    for i, db in enumerate(databases, 1):
        print(f"  {i}. {db['name']} ({db['size'] / 1024:.1f} KB)")

    # Confirm
    print()
    response = input(f"Upload {len(databases)} databases to Turso? (y/n): ")

    if response.lower() != 'y':
        print("Cancelled.")
        sys.exit(0)

    # Upload each database
    success_count = 0
    failed = []

    for db_info in databases:
        if upload_database(db_info):
            success_count += 1
        else:
            failed.append(db_info["name"])

    # Summary
    print(f"\n{'='*60}")
    print("UPLOAD SUMMARY")
    print(f"{'='*60}")
    print(f"Successful: {success_count}/{len(databases)}")

    if failed:
        print(f"Failed: {len(failed)}")
        print("Failed databases:")
        for name in failed:
            print(f"  - {name}")

    # Generate tokens
    if success_count > 0:
        response = input("\nGenerate auth tokens for uploaded databases? (y/n): ")
        if response.lower() == 'y':
            # Only generate tokens for successfully uploaded databases
            successful_dbs = [db for db in databases if db["name"] not in failed]
            generate_token_file(successful_dbs)

    print(f"\n{'='*60}")
    print("Next steps:")
    print("1. Add tokens from .env.turso to your .env file")
    print("2. Run: python scripts/test_turso_connection.py")
    print("3. Run: python scripts/regenerate_all_semantic_layers.py --source turso")
    print(f"{'='*60}")


if __name__ == "__main__":
    main()
